services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: event-root
      POSTGRES_PASSWORD: event-root
      POSTGRES_DB: event-root
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: .  # This specifies the current directory as the build context
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: event-root
      DATABASE_PASS: event-root
      DATABASE_NAME: event-root
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres-data:
